{
 "title": "Milestone_3",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "LOGS",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{app=~\"nginx|backend|db\"} | logfmt | line_format `{{.app}} -- {{.log}}`"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{app=~\".+\"} | logfmt | source = `stderr` | line_format `{{.app}} - {{.log}}`"
    }
   ]
  },
  {
   "title": "High Response Time Requests",
   "type": "logs",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{app=\"nginx\"} | logfmt | request_time >= 3 | line_format `{{.request}} {{.status}} - {{.upstream_addr}} {{.upstream_response_time}}`"
    }
   ]
  },
  {
   "title": "CPU Idle percent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (node_id, node_name) (\n    irate(node_cpu_seconds_total{mode=\"idle\"}[30m])\n    * on(instance) group_left(node_id,node_name)\n    node_meta\n) * 100)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Running Containers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{job=\"cadvisor\", name!=\"\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tile Server Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"milestone_3_tile-server.*\"}[1m])) by (id,name)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"milestone_3_db.*\"}[1m])) by (id,name)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"milestone_3_nginx.*\"}[1m])) by (id,name)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"milestone_3_backend.*\"}[1m])) by (id,name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}